/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.6
 * Generated at: 2021-09-28 16:55:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class viewSeedlingsAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Seedlings available in the farm include</title>\n");
      out.write("            <link href=\"bootstrap/css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <style>\n");
      out.write("            body{\n");
      out.write("                margin-left: 200px;\n");
      out.write("                float: center;\n");
      out.write("                background-image: linear-gradient(rgba(4,30,9,0.7),rgba(4,30,9,0.7)),url(images/apple1.png);\n");
      out.write("            }\n");
      out.write("            .col-sm-8{\n");
      out.write("                background-position: center;\n");
      out.write("                position: relative;\n");
      out.write("            }\n");
      out.write("            p{\n");
      out.write("                text-align: center;\n");
      out.write("                font-size: 50px;\n");
      out.write("                color: #fff;\n");
      out.write("            }\n");
      out.write("            .col-sm-8 .panel-body th{\n");
      out.write("                color: #fff;\n");
      out.write("            }\n");
      out.write("            .col-sm-8 .panel-body table{\n");
      out.write("                width: 100%;\n");
      out.write("            }\n");
      out.write("            .col-sm-8 .panel-body td{\n");
      out.write("                color: #fff;\n");
      out.write("            }\n");
      out.write("            .heading{\n");
      out.write("                float: center;\n");
      out.write("                color: #fff;\n");
      out.write("                align-items: center;\n");
      out.write("            }\n");
      out.write("            view1{\n");
      out.write("                   min-height: 100vh;\n");
      out.write("    width: 100%;\n");
      out.write("    background-image: linear-gradient(rgba(4,9,30,0.7),rgba(1,2,30,0.7)),url(images/apple1.png);\n");
      out.write("   \n");
      out.write("    background-position: center;\n");
      out.write("    background-size: cover;\n");
      out.write("    position: relative;\n");
      out.write("\n");
      out.write("            }\n");
      out.write("            .btn-close{\n");
      out.write("                border: 10px;\n");
      out.write("                color: #fff;\n");
      out.write("                border-radius: 100%;\n");
      out.write("            }\n");
      out.write("            .btn-close:hover{\n");
      out.write("                color: green;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("     \n");
      out.write("        <section class=\"view1\">\n");
      out.write("            \n");
      out.write("    <p>Seedlings available </p>\n");
      out.write("                 <div class=\"col-sm-8\">\n");
      out.write("                <div class=\"panel-body\">\n");
      out.write("                    <table id=\"tbl-student\" class=\"table table-responsive table-bordered\" cellpadding=\"0\" width=\"100%\">\n");
      out.write("                        <thead>\n");
      out.write("                            <tr>\n");
      out.write("                                <th>seedling id</th>\n");
      out.write("                                <th>Seedling name</th>\n");
      out.write("                                <th>Scientific name</th>\n");
      out.write("                                <th>variety</th>\n");
      out.write("                                <th>price</th>\n");
      out.write("                                <th>Number of seedlings</th>\n");
      out.write("                            </tr>\n");
      out.write("                            \n");
      out.write("                            \n");
      out.write("                            ");

                                /*
                            
                                    Connection conn;
    Statement stmt;
    ResultSet rs;
    
    String password = "q123";
    String userName = "root";
    String dbName = "Archotel";
    
    Class.forName("com.mysql.jdbc.Driver");
    conn = DriverManager.getConnection("jdbc:mysql://localhost/"+dbName,userName,password);
   stmt = conn.createStatement();
   rs = stmt.executeQuery("select * from rooms order by roomnumber");
   
while(rs.next()){
    String id = rs.getString("id");

   //<%= rs.getString("name") 
                                
                                

*/
                            
      out.write("\n");
      out.write("                            <tr>\n");
      out.write("                                <td>1</td>\n");
      out.write("                                <td>Avocado</td>\n");
      out.write("                                <td>Persea americana</td>\n");
      out.write("                                <td>fuete</td>\n");
      out.write("                                <td>ksh. 99</td>\n");
      out.write("                                <td>500</td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <td>2</td>\n");
      out.write("                                <td>Mango</td>\n");
      out.write("                                <td>Mangifera indica</td>\n");
      out.write("                                <td>kent</td>\n");
      out.write("                                <td>ksh. 99</td>\n");
      out.write("                                <td>5200</td>\n");
      out.write("                            </tr>\n");
      out.write("                            \n");
      out.write("                            <tr>\n");
      out.write("                                <td>3</td>\n");
      out.write("                                <td>Eucalyptus</td>\n");
      out.write("                                <td>Eucalyptus saligna</td>\n");
      out.write("                                <td>exotic</td>\n");
      out.write("                                <td>ksh. 50</td>\n");
      out.write("                                <td>5000</td>\n");
      out.write("                            </tr>\n");
      out.write("                              <tr>\n");
      out.write("                                <td>4</td>\n");
      out.write("                                <td>Apple</td>\n");
      out.write("                                <td>Malus domestica</td>\n");
      out.write("                                <td>Crips pink</td>\n");
      out.write("                                <td>ksh. 250</td>\n");
      out.write("                                <td>1000</td>\n");
      out.write("                            </tr>\n");
      out.write("                            \n");
      out.write("                        </thead>\n");
      out.write("                    </table>\n");
      out.write("                </div>\n");
      out.write("                            \n");
      out.write("                            <div> \n");
      out.write("                                <a href=\"index.html\" class=\"btn-close\">close</a>\n");
      out.write("                            </div>\n");
      out.write("            </div>\n");
      out.write("                            \n");
      out.write("                            </section>     \n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
